### PR TITLE
upgrade systemjs-builder to 0.9.1

### PR DESCRIPTION
**Pull request by lookfirst**

### CODE REVIEW

**Comment by amcdnl** [comment]
@marjan-georgiev can you test this against our project to make sure nothing breaks.

**Comment by lookfirst** [comment]
I'll test this too...

**Comment by amcdnl** [comment]
anyone got feedback?

**Comment by lookfirst** [comment]
It is mostly working. I've been struggling with getting everything working with latest jspm. I'm close though.

**Comment by lookfirst** [comment]
This is now out of date.

**Pull request closed without merging**
